services:
  - type: web
    name: django-class-demo
    runtime: python
    rootDir: myproject
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2
