# Generated by Django 6.0.6 on 2026-06-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollnumber',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
