# Generated by Django 6.0.6 on 2026-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
